### ISSUE TITLE
31_SCTransform.Rmd

### ISSUE THREAD

**Issue by katsikora** [maxplanck-ie/Rseurat#122]
```
library(SeuratData)
Error in library(SeuratData) : there is no package called ‘SeuratData’
> .libPaths()
[1] "/scratch/local/rseurat/pkg-lib-4.2.3" "/opt/R/4.2.3/lib/R/library" 
```

**Comment by adRn-s** [comment]
@NavandarM I think we forgot about this package.

I have copied it now, from my library. This is very prone to error, without resolving or checking dependencies. Though I did copy 3 seurat data folders that were in my library (that is, including ifnb and pbmc3k datasets)

**Comment by adRn-s** [comment]
copied over again, everything is there now
