### ISSUE TITLE
https://www.polleverywhere.com/multiple_choice_polls/O37srTQWC3KxHEP5Mtok1 correct answer is missing

### ISSUE THREAD

**Issue by katsikora** [maxplanck-ie/Rseurat#127]
Through two different approaches, I obtain `976` cells with <=2000 RNA counts. This answer is missing from the poll options.

approach 1:
```
sum(pbmc@meta.data$nCount_RNA<=2000)
```

approach 2:
```
a<-LayerData(pbmc,assay="RNA",layer="counts")
sum(colSums(a)<=2000)
```

**Comment by adRn-s** [comment]
`(colSums(pbmc.data) <= 2000) %>% sum()`

Yeah. I think I recall this happening on the course too.

Is there any filtering when we move from pbmc.data (raw counts matrix iirc); to the seurat object that you are using? Please add 976 as an option. Finding the underlying difference would be relevant to know if both are correct or what.

This kind of "difficulties" with the polls are highly appreciated by me, it allows us to show how things work underneath.

**Comment by katsikora** [comment]
Adrian, I'm just rerunning the exact same Rmd from last year and trying to emulate participant experience :)

**Comment by katsikora** [comment]
On my side, I was wondering if anything changed on the side of the bundled data, as we've updated packages. I'm not going to spend time on this though .
