### ISSUE TITLE
Variable Feature ordering has changed  -> update poll https://PollEv.com/multiple_choice_polls/K3MKnt5OsuhryxPCb4J1I/respond

### ISSUE THREAD

**Issue by katsikora** [maxplanck-ie/Rseurat#131]
2023/Seurat v4: correct response: LYZ, S100A9, PPBP

2024/Seurat v5: "PPBP"   "LYZ"    "S100A9"

**Comment by adRn-s** [comment]
I will fix the CSV file that will be uploaded to pollev website.
Beware that any changes to pollev website will be overwritten by csv files. Meaning, all fixes go into csv files.

**Comment by katsikora** [comment]
Hi Adrian, please don't fix the poll csv file for 14... - I've committed changes to it and I'd expect merge conflicts if you do that as well.
Thanks!

**Comment by katsikora** [comment]
Please feel free to update csvs for polls from the modules you're going to teach -  I wonder if there are any surprises there.
