### ISSUE TITLE
polls/16_UMAP.csv

### ISSUE THREAD

**Issue by thomasmanke** [maxplanck-ie/Rseurat#92]
line 4: sensible --> sensitive.   also remove "UMAP counteracts ..." (unclear)
line 5: just double-checking. do you really want them to change FindNeighbours? Potentially confusing, perhaps it should be clarified what would be considered 'better'

**Comment by adRn-s** [comment]
line 4: done

line 5: my bad, I surely wanted to write 'dimensional reduction algorithms'... I will specify UMAP now.

By 'better' I wanted them to convey that a very low number of PCs (e.g. 4) would be 'bad'. This may be clearer in the new set of optional answers.
